accesscorgis_wpgsql/config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :corgis
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('corgis/#index')

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'
end

accesscorgis_wpgsql/app/models/product.rb
class Product < ApplicationRecord

  has_many :product_categories
  has_many :categories, through: :product_categories

  has_many :variants, class_name: 'ProductVariant'

end

accesscorgis_wpgsql/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.includes(:variants).order(:title)
  end

end

accesscorgis_wpgsql/app/views/products/index.html.erb
<h2>
  <%= link_to "Categories", root_path %> /
  <%= @category.title %> /
  Products
</h2>

<ol>
  <% @products.each do |product| %>
    <li>
      <%= product.title %> (<%= number_to_currency product.price %>)

      <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, 1 %>
        <%= submit_tag "Add to Cart" %>
      <% end %>

      <ul>
        <% product.variants.each do |variant| %>
          <li><%= variant.title %> (<%= number_to_currency variant.price %>)</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>